version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    groups:
      aws-clients:
        dependency-type: production
        patterns:
          - '@aws-sdk/*'
    ignore:
      # update-dependencies workflow already handles minor/patch updates
      - dependency-name: '*'
        update-types:
          - version-update:semver-minor
          - version-update:semver-patch
