version: 2
updates:
  - package-ecosystem: npm
    open-pull-requests-limit: 99
    directory: /
    schedule:
      interval: weekly
      time: '08:00'
      timezone: America/Toronto
    versioning-strategy: increase
    reviewers:
      - Brightspace/quality-enablement-reviewers
    ignore:
      - dependency-name: '*'
        update-types: ['version-update:semver-patch']
      # Remove after eslint 9 stops throwing npm i errors
      - dependency-name: eslint
        versions: '>= 9'
    groups:
      aws-clients:
        dependency-type: production
        patterns:
          - '@aws-sdk/*'
      eslint:
        dependency-type: development
        patterns:
          - eslint
          - eslint-*
