name: Test Reporting
description: Report testing data from directly in your GitHub Action runs
author: D2L Corporation
inputs:
  aws-access-key-id:
    description: Specifies an AWS access key associated with an IAM account
    required: true
  aws-secret-access-key:
    description: Specifies the secret key associated with the access key. This is essentially the "password" for the access key
    required: true
  aws-session-token:
    description: Specifies the session token value that is required if you are using temporary security credentials that you retrieved directly from AWS STS operations
    required: true
  role-to-assume:
    description: The Amazon Resource Name (ARN) of the role to assume. Use the provided credentials to assume an IAM role and configure the Actions environment with the assumed role credentials rather than with the provided credentials
    default: arn:aws:iam::427469055187:role/github+${{github.repository_owner == 'BrightspaceHypermediaComponents' && 'BHC' || github.repository_owner}}+${{github.event.repository.name}}
  report-path:
    description: Path to report D2L format test report JSON file
    required: true
    default: ./d2l-test-report.json
  lms-build-number:
    description: LMS build number used in the generation of this report
    required: false
  lms-instance-url:
    description: LMS instance URL used in the generation of this report
    required: false
  inject-github-context:
    description: Change mode for injection of GitHub Actions context at report submission time
    required: true
    default: auto
  dry-run:
    description: Run action in dry run mode. Will perform all operations except final submission of report data to backend
    required: true
    default: false
  debug:
    description: Enable or disable debug mode. Will enable additional log messages. Does not stop final submission of report data to backend
    required: true
    default: false
runs:
  using: node20
  main: dist/index.js
