name: Test Reporting
description: Report testing data from directly in your GitHub Action runs
author: D2L Corporation
inputs:
  aws-access-key-id:
    description: AWS Access Key ID. This input is required if running in the GitHub hosted environment
    required: true
  aws-secret-access-key:
    description: AWS Secret Access Key. This input is required if running in the GitHub hosted environment
    required: true
  aws-session-token:
    description: AWS Session Token
    required: true
  report-path:
    description: Path to report JSON file
    required: true
    default: ./d2l-test-report.json
  inject-github-context:
    description: Change injection of GitHub Actions context at report submission time
    required: true
    default: auto
  dry-run:
    description: Run action in dry run mode
    required: true
    default: false
  debug:
    description: Run action in debug mode. Will enable additional logging messages
    required: true
    default: false
runs:
  using: node20
  main: dist/index.js
